### PR TITLE
[medium]Feature/27

### PR DESCRIPTION
**Pull request by josdem**
- Ading a class to filter pets waiting for vaccines
- Adding a class to create vaccination records based on pet's birthdate
- Adding test cases
- Adding expected tables and rows
- Updating to release version 🎉

### CODE REVIEW

**Comment by josdem** [comment]
@kaminuma / @jgafnea 

Hello, I still need to fix Sonarcloud issues found here: https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&pullRequest=39&id=josdem_py-vetlog-analyzer however, I do not have time today, so I will do tomorrow.

**Comment by kaminuma** [comment]
Hi @josdem 
There are a few things I would like to ask you. Up until now, we have been reviewing the code base, but we are now preparing to prepare an actual environment and check its operation.

`python -m unittest discover -s tests`

When I run it, it fails with a MySQL connection error.

As I understand it, with the Vetlog DB started,

```class Connector:
    def __init__(self):
        self.connection = mysql.connector.connect(
            host=os.getenv("HOST"),
            user=os.getenv("VETLOG_USER"),
            password=os.getenv("VETLOG_PASSWORD"),
            database=os.getenv("DATABASE"),
```

Isn't it okay just to rewrite the settings?

If there is an explanation somewhere, please let me know.

**Comment by josdem** [comment]
> Hi @josdem There are a few things I would like to ask you. Up until now, we have been reviewing the code base, but we are now preparing to prepare an actual environment and check its operation.
> 
> `python -m unittest discover -s tests`
> 
> When I run it, it fails with a MySQL connection error.
> 
> As I understand it, with the Vetlog DB started,
> 
> ```
>     def __init__(self):
>         self.connection = mysql.connector.connect(
>             host=os.getenv("HOST"),
>             user=os.getenv("VETLOG_USER"),
>             password=os.getenv("VETLOG_PASSWORD"),
>             database=os.getenv("DATABASE"),
> ```
> 
> Isn't it okay just to rewrite the settings?
> 
> If there is an explanation somewhere, please let me know.

Hi @kaminuma yes, we have instructions to set up the database credentials, please find them here: https://github.com/josdem/py-vetlog-analyzer/wiki/Configuration let me know if is not working as expected.

**Comment by kaminuma** [comment]
@josdem 
thank you!!

It seems that there was some problem because the env file could not be found and it was written directly to the environment variable.
I solved it and passed the test.

スクリーンショット 2024-10-19 000616

I approved

**Review by kaminuma — APPROVED** [review]

**Comment by josdem** [comment]
> @josdem thank you!!
> 
> It seems that there was some problem because the env file could not be found and it was written directly to the environment variable. I solved it and passed the test.
> 
> スクリーンショット 2024-10-19 000616
> 
> I approved

Nice, thank you!

**Pull request merged**
